Repository softeerbootcamp/Team3, pull requests merged in 2023-02, with the labels that each got.

#29 Feature/14/register config
  frontend/gathergo/src/Register/register.css
  frontend/gathergo/src/Register/register.html
  frontend/gathergo/src/login/login.css
  frontend/gathergo/src/login/login.html
Labels: design

#33 feat : profile, profile 편집 (#30)
  frontend/gathergo/assets/profileEdit.svg
  frontend/gathergo/src/Profile/profile.css
  frontend/gathergo/src/Profile/profile.html
  frontend/gathergo/src/Profile/profile.ts
Labels: design

#46 Fix/30/profile UI
  frontend/gathergo/assets/profileEdit.svg
  frontend/gathergo/package-lock.json
  frontend/gathergo/src/Profile/profile.css
  frontend/gathergo/src/Profile/profile.html
Labels: bug, design

#55 Redesign/12/login UI
  frontend/gathergo/src/Profile/profile.css
  frontend/gathergo/src/Profile/profile.html
  frontend/gathergo/src/login/login.css
  frontend/gathergo/src/login/login.html
  frontend/gathergo/src/login/login.ts
Labels: feature, design

#57 #56 initialstate.ts 작성
  frontend/gathergo/initialstate.ts
Labels: feature

#63 design/60/notice
  frontend/gathergo/index.html
  frontend/gathergo/src/Index/index.ts
  frontend/gathergo/src/Index/notice.css
  frontend/gathergo/src/Index/notice.css.map
  frontend/gathergo/src/Index/notice.scss
  frontend/gathergo/src/Profile/profile.css
  frontend/gathergo/src/Profile/profile.html
Labels: design

#60 [Resolve #44] 로그아웃 구현
  backend/gathergo/src/main/java/lightning/gathergo/controller/AuthController.java
  backend/gathergo/src/main/java/lightning/gathergo/exception/ErrorCode.java
  backend/gathergo/src/main/java/lightning/gathergo/exception/GlobalExceptionHandler.java
  backend/gathergo/src/main/java/lightning/gathergo/repository/SessionRepository.java
  backend/gathergo/src/main/java/lightning/gathergo/service/CookieService.java
  backend/gathergo/src/main/java/lightning/gathergo/service/SessionService.java
  backend/gathergo/src/main/java/lightning/gathergo/service/UserService.java
  backend/gathergo/src/test/java/lightning/gathergo/controller/AuthControllerTest.java
  backend/gathergo/src/test/java/lightning/gathergo/repository/SessionRepositoryTest.java
Labels: feature

#72 [디자인] 댓글 삭제 모달 띄우기
  frontend/gathergo/README.md
  frontend/gathergo/assets/Icons/setting icon.png
  frontend/gathergo/checkmodal/checkmodal.css
  frontend/gathergo/checkmodal/checkmodal.ts
  frontend/gathergo/checkmodal/checkmodalEvent.ts
  frontend/gathergo/index.html
  frontend/gathergo/src/Index/notice.css.map
  frontend/gathergo/src/Index/notice.scss
Labels: design

#85 Error modal
  frontend/gathergo/index.html
  frontend/gathergo/src/components/modals/errorModal.ts
  frontend/gathergo/src/css/errormodal.css
Labels: design

#100 feat: 서버와의 연결 준비 -댓글 생성,
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/common/constants.ts
  frontend/gathergo/src/components/card/CardList.ts
  frontend/gathergo/src/components/card/CardModal.ts
  frontend/gathergo/src/components/comment/CommentList.ts
  frontend/gathergo/src/components/dropdown/dropdownCategory.ts
  frontend/gathergo/src/components/dropdown/dropdownRegion.ts
  frontend/gathergo/src/components/form/postingForms/MapForm.ts
  frontend/gathergo/src/components/header/headerHome.ts
  frontend/gathergo/src/components/header/headerSearchSticky.ts
  frontend/gathergo/src/components/modals/notiModal.ts
  frontend/gathergo/src/css/feedRead.css
  frontend/gathergo/src/css/notiModal.css
  frontend/gathergo/src/pages/home.ts
  frontend/gathergo/src/server/initialstate.ts
  frontend/gathergo/src/store/actions.ts
  frontend/gathergo/src/store/reducers.ts
Labels: feature, refactor

#134 Profile page
  frontend/gathergo/Profile/profile.css
  frontend/gathergo/Profile/profile.html
  frontend/gathergo/Profile/profile.ts
  frontend/gathergo/index.html
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/common/constants.ts
  frontend/gathergo/src/components/profile/profileLayout.ts
  frontend/gathergo/src/components/profile/profileMain.ts
  frontend/gathergo/src/components/profile/profileSidebar.ts
  frontend/gathergo/src/components/profile/tabEditMain.ts
  frontend/gathergo/src/components/profile/tabLogoutModal.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserDesc.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserHost.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserHostList.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserInfo.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserJoin.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserJoinList.ts
  frontend/gathergo/src/components/profile/tabProfileMain.ts
  frontend/gathergo/src/css/profile.css
  frontend/gathergo/src/pages/profile.ts
  frontend/gathergo/src/server/initialstate.ts
  frontend/gathergo/src/store/actions.ts
  frontend/gathergo/src/store/reducers.ts
Labels: bug, feature, design

#149 프로파일 페이지 요청
  frontend/gathergo/checkmodal/checkmodal.css
  frontend/gathergo/checkmodal/checkmodal.ts
  frontend/gathergo/checkmodal/checkmodalEvent.ts
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/common/constants.ts
  frontend/gathergo/src/components/profile/tabEditMain.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserDesc.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserHost.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserInfo.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserJoin.ts
  frontend/gathergo/src/components/profile/tabProfileMain.ts
  frontend/gathergo/src/server/initialstate.ts
  frontend/gathergo/src/store/actions.ts
  frontend/gathergo/src/store/reducers.ts
Labels: design

#155 프로필 일부 수정
  frontend/gathergo/Profile/profile.css
  frontend/gathergo/Profile/profile.html
  frontend/gathergo/Profile/profile.ts
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/components/profile/profileMain.ts
  frontend/gathergo/src/components/profile/tabEditMain.ts
  frontend/gathergo/src/components/profile/tabLogoutModal.ts
  frontend/gathergo/src/components/sidebar/alarmSidebar.ts
  frontend/gathergo/src/css/profile.css
  frontend/gathergo/src/pages/profile.ts
  frontend/gathergo/src/store/reducers.ts
Labels: design

#165 #164 로그아웃 버그 수정
  frontend/gathergo/src/components/profile/tabEditMain.ts
  frontend/gathergo/src/components/profile/tabLogoutModal.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserInfo.ts
  frontend/gathergo/src/css/profile.css
Labels: bug

#169 Profile 이미지 Card에서 출력안되는 버그 수정
  frontend/gathergo/src/common/constants.ts
  frontend/gathergo/src/components/card/CardModal.ts
  frontend/gathergo/src/components/profile/tabEditMain.ts
  frontend/gathergo/src/components/profile/tabLogoutModal.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserHost.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserInfo.ts
  frontend/gathergo/src/css/profile.css
  frontend/gathergo/src/server/initialstate.ts
Labels: bug

#171 README 업데이트, alarm 부분 html에 추가
  frontend/gathergo/README.md
  frontend/gathergo/index.html
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/common/constants.ts
  frontend/gathergo/src/components/card/CardModal.ts
  frontend/gathergo/src/components/profile/tabLogoutModal.ts
Labels: design

#183 Alarm onmessage
  frontend/gathergo/README.md
  frontend/gathergo/firebase-messaging-sw.js
  frontend/gathergo/index.html
  frontend/gathergo/package-lock.json
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/components/fba/chatBotOpenAI.js
  frontend/gathergo/src/css/profile.css
Labels: feature

#187 글 작성시 알람 구독, 프로필 글 클릭시 redirect
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/components/card/CardModal.ts
  frontend/gathergo/src/components/profile/profileLayout.ts
  frontend/gathergo/src/components/profile/profileMain.ts
  frontend/gathergo/src/components/profile/tabEditMain.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserHost.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserHostList.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserInfo.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserJoin.ts
  frontend/gathergo/src/components/profile/tabProfile/profileUserJoinList.ts
  frontend/gathergo/src/components/profile/tabProfileMain.ts
  frontend/gathergo/src/css/profile.css
  frontend/gathergo/src/pages/profile.ts
Labels: feature

#203 알람 사이드바 구현
  frontend/gathergo/src/common/Fetches.ts
  frontend/gathergo/src/common/constants.ts
  frontend/gathergo/src/components/sidebar/alarmSidebar.ts
  frontend/gathergo/src/components/sidebar/log.ts
  frontend/gathergo/src/css/profile.css
  frontend/gathergo/src/pages/home.ts
  frontend/gathergo/src/server/initialstate.ts
  frontend/gathergo/src/store/actions.ts
  frontend/gathergo/src/store/reducers.ts
Labels: deploy

#207 Css entry point
  frontend/gathergo/index.html
  frontend/gathergo/src/components/profile/tabProfile/profileUserJoin.ts
  frontend/gathergo/src/css/app.css
Labels: refactor
